### PR TITLE
Jamie/save multiple charts

### PR DESCRIPTION
**Pull request by charlesknightsbridge**
I'm confused. This shows all the commits leading up to the current Master, I think.
I merged all the changes to Master into this to make sure there was nothing missed out.

@torstenchr should I make a new branch and bring all of these changes in? I see that the changed files only include the newly changed ones. Please let me know what you want me to do here.

Pareto (in master) can create multiple chart pairs with the !by command. Now we can actually save these charts properly. At the moment, master cannot save charts from the command line (error) and saving from the chart dialog gives weird file names. I think I've used a reasonable way to manage this, with minimal changes to the save graph units.

And I just noticed that pareto has been added to command.html

### CODE REVIEW

**Comment by torstenchr** [comment]
I think the problem was that you merged the master into the branch instead or rebasing. They are two different methods and rebasing is often the preferred method  when the "master" branch is ahead of the current feature branch.
Rebasing a feature branch on the master branch can be done like this:

`git checkout <feature-brach>
git pull #make sure the feature branch is up-to-date
git fetch --all #update meta-data of all branches, including master
git rebase origin/master`

**Comment by charlesknightsbridge** [comment]
I looked at rebase; I’m sure I’ve done this before, but the conflict resolution left my head spinning. Reading a bit on Git help suggested to me that unless I really knew what I was doing, merge is safer. I can see in the pull request, the actual changes I’ve made are all confined to the last commit shown on that page. I could make a new branch from master and reproduce the changes. It will be a lot cleaner (without all the history of master), but…

I’m a bit reluctant to do anything, but whatever you think best, I’ll do (except when I looked at rebase, the conflicts seemed a challenge to get right).

I’m quite amazed that I even got this to work; I’d just about given up with the approach I was taking, but it all seems to make sense now.

**Comment by charlesknightsbridge** [comment]
I tried rebase and it ended up the same, with all of the commits from master included in the branch. EXCEPT I am not completely certain that other changes didn't creep in as I resolved all the conflicts.

**Comment by torstenchr** [comment]
I'm sorry Jamie, but it is really hard to see what you are working on here - are you trying to implement multiple features?

You are adding Stratum Values to a single chart, and adding thing into the pareto graph. Even the executor is getting things reworked...

The heading is "save multple charts" but that seems to be only part of this PR.

Is there some way you can separate the work into multiple smaller PR's that are more clear?

**Comment by charlesknightsbridge** [comment]
I'll see if I can break this up. 

There were previously some back end changes to support the !by option in charts. !by implies that there will be one chart for each stratum. This is different from the current display of multiple strata in a single chart (histogram, epicurve, bar, survival).

The !by requirement arose with pareto, where you cannot plot multiple strata on the same chart because the x-axis changes. To put them in the same graph frame would be possible, but becomes impractical if you have more than a couple of strata.

We already have multiple charts as tabs within the graph form. (part of the big merge for pareto)

My approach was:
1. define the back end support in graphexecutor and graphform (merged)
2. implement in pareto (save will fail) (merged)
3. implement graph save (this one)

I thought I had documented the changes. The trick was to get save files named in a simple, but logical, way (using the stratum value). I had originally used the stratum value label, but that was a bad idea. the stratum value is simpler. That's what led to changes in the back end for graphs.

**Comment by charlesknightsbridge** [comment]
splitting this up with branches based on today's master.

**Comment by charlesknightsbridge** [comment]
Hi Torsten,
I’m sending this outside of github…
I’ve just made a sequential series of pull requests implementing saving multiple charts from a single graph command. This only works for pareto.
The pull request build on each other — I based each new branch on the one in the previous pull request.
This breaks up that big PR and if you see something amiss as I went along, it will be easier to fix.
Cheers,
Jamie

**Pull request closed without merging**
