### PR TITLE
Added new !nouc option to import string as non-uppercase fields

### PR DESCRIPTION
**Pull request by torstenchr**

### CODE REVIEW

**Comment by torstenchr** [comment]
This will fail until PR (https://github.com/EpiData-dk/core/pull/21) is merged because it relies on a new property from Core.

**Comment by charlesknightsbridge** [comment]
Works as expected for me:

`.read !cb;
Lines: 8
Separators: (Tab: 2) (Semicolon: 0) (Comma: 0) (Space: 0) 
Separator found: 	
Loaded file: /Users/jamie/EpiData/(Not Saved)
Cycle: 0 Datasets: 1 Modified: 2024-06-05 4:46:19 PM 

.list v;
 Name Type      Length Decimal Label      Valuelabels Missing
 Date String    6      0       Date                          
 V2   String    68     0       Where/what                    
 Cost Uppercase 9      0        Cost                         
 
.close;
Project Closed!

.read !cb !nouc;
Lines: 8
Separators: (Tab: 2) (Semicolon: 0) (Comma: 0) (Space: 0) 
Separator found: 	
Loaded file: /Users/jamie/EpiData/(Not Saved)
Cycle: 0 Datasets: 1 Modified: 2024-06-05 4:46:58 PM 

.list v;
 Name Type   Length Decimal Label      Valuelabels Missing
 Date String 6      0       Date                          
 V2   String 68     0       Where/what                    
 Cost String 9      0        Cost   `

**Comment by torstenchr** [comment]
@charlesknightsbridge build succeeded now that the PR from Core was merged. PLease review.

**Review by charlesknightsbridge — APPROVED** [review]
Very straightforward...

**Pull request merged**
