### PR TITLE
Fix charts saved as svg

### PR DESCRIPTION
**Pull request by charlesknightsbridge**
Charts were not sized properly. Now, follow the same scheme as raster files using FGraphSize (1024 x 720)

### CODE REVIEW

**Comment by torstenchr** [comment]
This was intentionally implemented this way because I wanted to save the chart the same size as the window. But I guess that seen from a user perspective it is probably better to follow the same standard for all output types.
@JLepidata  do you have an opinion on this?

**Comment by charlesknightsbridge** [comment]
On my Mac, prior to this change, the .svg files came out at about 250 x 250 pixels and they did not scale up very well.. I don't know why.

**Comment by JLepidata** [comment]
Svg files should be vector graphics. Scalable Vector Graphics -
Or else I do not understand SVG

Best 
Jens

⁣Hent BlueMail til Android ​

Den 6. maj 2024 20.29, fra 20.29, Jamie ***@***.***> skrev:

**Comment by charlesknightsbridge** [comment]
They are. When saving via the dialog (right-click on a chart), they look fine, since they use the chart window size.
However, when saving from the command line, there is no window reference, so they don’t look right. Here’s an example that I opened with BoxySVG:

This may be because font sizes come from SET options and I have pareto set line widths appropriate for the default fonts.

**Review by torstenchr — APPROVED** [review]

**Comment by JLepidata** [comment]
I should make a formal request, but have no system here. Excuses 

If possible change import from clipboard to make string field NOT upper case. I am not sure if this is a core function 

/Jens

⁣Hent BlueMail til Android ​

Den 15. maj 2024 21.01, fra 21.01, Torsten Bonde Christiansen ***@***.***> skrev:

**Pull request merged**
