### PR TITLE
Implemented graphs feature:

### PR DESCRIPTION
**Pull request by torstenchr**
* Graphs are shown in a form or can be saved/exported
* Implemented first command 'scatter'

### CODE REVIEW

**Review by charlesknightsbridge — CHANGES_REQUESTED** [review]
I believe that we agreed to use !ti for the title and !fn for the footnote; I will add a commit that makes these changes. I've also addressed the Save As dialog, which suggests that SVG is the default file type if no file type is included in the file name. But the file type is not initialized, leading to an error.

**Comment by torstenchr** [comment]
@charlesknightsbridge It looks like you forgot to rebase on my branch before you applied you changes. It is always a good idea to rebase first, because otherwise it messes with the commit log. Merging a branch rather than rebasing introduces old commit messages and in addition to that it also adds the merge commit.

**Review by charlesknightsbridge — APPROVED** [review]
OK. Let's merge this and I'll suggest changes after.

**Comment by charlesknightsbridge** [comment]
Really not sure whether that was a good idea. I thought I was approving the changes as of your commit 4aa76a8. I won't click on the merge button, though, in case we have to do a revert first.
Still trying to get this right...

**Comment by torstenchr** [comment]
No worries - I will take a look at it during the weekend and squash the stuff together again ;)

**Pull request merged**
