### PR TITLE
Implemented survival analysis and KM plot.

### PR DESCRIPTION
**Pull request by torstenchr**

### CODE REVIEW

**Comment by charlesknightsbridge** [comment]
This compiles fine for me. For each compile the file epidataanalysis.res is missing or cannot be opened. I don't see it on git.

**Comment by torstenchr** [comment]
It is because i removed the .res file which is generated by Lazarus when you code normally. But on the build system lazarus is only used as a dependency/library which does not created the .res file.
I will add it again later today  to fix this.

**Comment by torstenchr** [comment]
I'm not sure this PR is ready because the output does not match that of EpiData Analysis Classic. The output can be seen in the links below. @JLepidata will you please comment on this!

Survival PR:
https://pastebin.com/eVsv9S6R

Lifetable (classic):
https://pastebin.com/PTXQLB4Q

**Comment by charlesknightsbridge** [comment]
I wasn't trying to replicate classic analysis (since I have no way to run it)
My reference for survival analysis: https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Survival/BS704_Survival_print.html
Some of their tables also have number lost to follow up. That is easy to implement and has the benefit of being able to add short vertical lines at points where there was loss to follow up, as is done in some stat software.

**Comment by torstenchr** [comment]
Okay - I know that Jens spent a lot of time getting the representation of data the way it is in classic analysis. Code-wise I think this pull request is as it should be now.

**Review by charlesknightsbridge — APPROVED** [review]
Output to be reviewed as we move forward. Torsten and I agree this is good to go.

**Pull request merged**
