### PR TITLE
Fix MacOS menu changes

### PR DESCRIPTION
**Pull request by charlesknightsbridge**

### CODE REVIEW

**Comment by charlesknightsbridge** [comment]
Changes to MacOS menus had a dependency on the order of main menu items. This caused failure when the Graph menu was added. The changes are now made without direct reference to MainMenu.Items, so this won't happen again.

**Comment by torstenchr** [comment]
How is this PR related to the general menu name changes? It seems like this is also changed in the "rational menu object names" branch?

**Comment by charlesknightsbridge** [comment]
You are right. I did a better job of the Mac menus in the rational menu… branch.

Jamie

**Comment by torstenchr** [comment]
> [](#)

Great - will you delete this branch then.

**Pull request closed without merging**
